name: CI Checks

on: [push, pull_request]

jobs:
  audit:
    name: Check npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm audit
        env:
          CI: true
  cql4browsers:
    name: Check cql4browsers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: ./bin/validate_cql4browsers.sh
        env:
          CI: true
  lint:
    name: Check lint and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
        env:
          CI: true
  test:
    name: Test on node 18 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Set timezone to America/New_York
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York
      - run: date +"%Y-%m-%d %T"
      - run: npm install
      - run: ./bin/check_for_nonassertive_tests.sh
      - run: npx nyc --reporter=lcov npm test
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
